spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 200ms
          multiplier: 2.0
          max-interval: 2000ms
